const state={token:localStorage.getItem("nexgene_token"),mode:"login"};const $=id=>document.getElementById(id);const screens=["auth","home","morning","evening","timeline","insights"];
function show(id){screens.forEach(s=>$(s).hidden=s!==id)}
async function api(path,opts={}){const headers={"Content-Type":"application/json",...(opts.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(`/api/v1${path}`,{...opts,headers});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={detail:text}}if(!res.ok)throw new Error((data&&data.detail)||res.statusText);return data}
function setAuthMode(mode){state.mode=mode;$("tab-login").classList.toggle("active",mode==="login");$("tab-register").classList.toggle("active",mode==="register");$("auth-submit").textContent=mode==="login"?"Log in":"Create account"}
async function bootstrap(){if(!state.token){show("auth");return}try{const me=await api("/auth/me");$("who").textContent=me.email;show("home")}catch{localStorage.removeItem("nexgene_token");state.token=null;show("auth")}}
$("tab-login").onclick=()=>setAuthMode("login");$("tab-register").onclick=()=>setAuthMode("register");
$("auth-form").onsubmit=async e=>{e.preventDefault();$("auth-error").hidden=true;try{const body={email:$("email").value.trim(),password:$("password").value};const data=await api(`/auth/${state.mode}`,{method:"POST",body:JSON.stringify(body)});state.token=data.access_token;localStorage.setItem("nexgene_token",state.token);await bootstrap()}catch(err){$("auth-error").textContent=err.message;$("auth-error").hidden=false}};
$("logout").onclick=()=>{state.token=null;localStorage.removeItem("nexgene_token");show("auth")};
document.querySelectorAll("[data-open]").forEach(btn=>btn.onclick=()=>show(btn.dataset.open));
document.querySelectorAll("[data-back]").forEach(btn=>btn.onclick=()=>show("home"));
async function submitCheckin(formId,mode){const form=$(formId);const fd=new FormData(form);const body={};for(const[k,v]of fd.entries()){if(v==="")continue;body[k]=["sleep_duration","activity_duration"].includes(k)?Number(v):Number(v)}await api(`/checkins/${mode}`,{method:"POST",body:JSON.stringify(body)});form.reset();show("home");alert(`${mode} check-in saved`)}
$("morning-form").onsubmit=async e=>{e.preventDefault();try{await submitCheckin("morning-form","morning")}catch(err){alert(err.message)}};
$("evening-form").onsubmit=async e=>{e.preventDefault();try{await submitCheckin("evening-form","evening")}catch(err){alert(err.message)}};
async function loadTimeline(){const rows=await api("/timeline");const el=$("timeline-list");if(!rows.length){el.innerHTML='<div class="item"><strong>No entries yet</strong><span>Complete a morning or evening check-in.</span></div>';return}el.innerHTML=rows.map(r=>`<div class="item"><strong>${r.observation_type}</strong><span>${new Date(r.recorded_at).toLocaleString()} · ${r.value}</span></div>`).join("")}
async function loadInsights(){const rows=await api("/checkins/insights");const el=$("insights-list");if(!rows.length){el.innerHTML='<div class="item"><strong>No insights yet</strong><span>Keep logging for a few days to surface trends.</span></div>';return}el.innerHTML=rows.map(r=>`<div class="item"><strong>${r.title}</strong><span>${r.message}</span></div>`).join("")}
document.querySelector('[data-open="timeline"]').addEventListener("click",()=>loadTimeline().catch(err=>alert(err.message)));
document.querySelector('[data-open="insights"]').addEventListener("click",()=>loadInsights().catch(err=>alert(err.message)));
setAuthMode("login");bootstrap();
